### PR TITLE
Fix clang build

### LINKED ISSUE #109: Fails to build with Clang
Regressed by af54c04bc6a4 (#83)
```c++
../grid/grid_tools.cc:204:22: error: 'dest' in capture list does not name a variable
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                     ^
../grid/grid_tools.cc:204:28: error: 'pos' in capture list does not name a variable
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                           ^
../grid/grid_tools.cc:204:50: error: reference to local binding 'dest' declared in enclosing function 'desktop_entry'
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                                                 ^
../grid/grid_tools.cc:200:29: note: 'dest' declared here
        for (auto& [prefix, dest, tag] : matches) {
                            ^
../grid/grid_tools.cc:204:69: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                                                                    ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
../grid/grid_tools.cc:205:22: error: 'dest' in capture list does not name a variable
                    [dest, pos, &view](cut_t) {
                     ^
../grid/grid_tools.cc:205:28: error: 'pos' in capture list does not name a variable
                    [dest, pos, &view](cut_t) {
                           ^
../grid/grid_tools.cc:206:52: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                        auto idx = view.find(" %", pos);
                                                   ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
../grid/grid_tools.cc:210:26: error: reference to local binding 'dest' declared in enclosing function 'desktop_entry'
                        *dest = view.substr(pos, idx - pos);
                         ^
../grid/grid_tools.cc:200:29: note: 'dest' declared here
        for (auto& [prefix, dest, tag] : matches) {
                            ^
../grid/grid_tools.cc:210:45: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                        *dest = view.substr(pos, idx - pos);
                                            ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
../grid/grid_tools.cc:210:56: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                        *dest = view.substr(pos, idx - pos);
                                                       ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
10 errors generated.
```

### PR DESCRIPTION
**Pull request by Siborgium**
Should fix #109

### CODE REVIEW

**Comment by jbeich** [comment]
Clang would've accepted the following as well:
```diff
--- a/grid/grid_tools.cc
+++ b/grid/grid_tools.cc
@@ -201,8 +201,8 @@ std::optional<DesktopEntry> desktop_entry(std::string&& path, const std::string&
             auto [ok, pos] = try_strip_prefix(prefix);
             if (ok) {
                 std::visit(visitor {
-                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
-                    [dest, pos, &view](cut_t) {
+                    [dest = dest, pos = pos, &view](nop_t) { *dest = view.substr(pos); },
+                    [dest = dest, pos = pos, &view](cut_t) {
                         auto idx = view.find(" %", pos);
                         if (idx == std::string_view::npos) {
                             idx = std::size(view);
```

**Comment by Siborgium** [comment]
The issue with clang is not copying, it's that variables inside of structured bindings are not exactly variables. However, your solution is much cleaner. I'll use it in my local copy and hopefully merge into master with the next PR.

**Comment by nwg-piotr** [comment]
@Siborgium do not forget to sync other PRs merged lately.
