### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [nwg-piotr/nwg-launchers#109]
Regressed by af54c04bc6a4 (#83)
```c++
../grid/grid_tools.cc:204:22: error: 'dest' in capture list does not name a variable
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                     ^
../grid/grid_tools.cc:204:28: error: 'pos' in capture list does not name a variable
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                           ^
../grid/grid_tools.cc:204:50: error: reference to local binding 'dest' declared in enclosing function 'desktop_entry'
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                                                 ^
../grid/grid_tools.cc:200:29: note: 'dest' declared here
        for (auto& [prefix, dest, tag] : matches) {
                            ^
../grid/grid_tools.cc:204:69: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                    [dest, pos, &view](nop_t) { *dest = view.substr(pos); },
                                                                    ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
../grid/grid_tools.cc:205:22: error: 'dest' in capture list does not name a variable
                    [dest, pos, &view](cut_t) {
                     ^
../grid/grid_tools.cc:205:28: error: 'pos' in capture list does not name a variable
                    [dest, pos, &view](cut_t) {
                           ^
../grid/grid_tools.cc:206:52: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                        auto idx = view.find(" %", pos);
                                                   ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
../grid/grid_tools.cc:210:26: error: reference to local binding 'dest' declared in enclosing function 'desktop_entry'
                        *dest = view.substr(pos, idx - pos);
                         ^
../grid/grid_tools.cc:200:29: note: 'dest' declared here
        for (auto& [prefix, dest, tag] : matches) {
                            ^
../grid/grid_tools.cc:210:45: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                        *dest = view.substr(pos, idx - pos);
                                            ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
../grid/grid_tools.cc:210:56: error: reference to local binding 'pos' declared in enclosing function 'desktop_entry'
                        *dest = view.substr(pos, idx - pos);
                                                       ^
../grid/grid_tools.cc:201:23: note: 'pos' declared here
            auto [ok, pos] = try_strip_prefix(prefix);
                      ^
10 errors generated.
```

**Comment by Siborgium** [comment]
This is some dumb shit, thanks clang. It fails to capture variable declared in structured binding because it does not even consider it a variable.

**Comment by nwg-piotr** [comment]
@Siborgium Thank you! Do you think we should keep CI on, and add builds for another OSes? I have no experience with Travis.

**Comment by Siborgium** [comment]
Sure, why not? I'd look into Github CI, but Travis will do.
